// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: binance.proto

package finazon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BinanceService_GetTimeSeries_FullMethodName = "/finazon.BinanceService/GetTimeSeries"
)

// BinanceServiceClient is the client API for BinanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BinanceServiceClient interface {
	// Get time series data without technical indicators
	GetTimeSeries(ctx context.Context, in *GetBinanceTimeSeriesRequest, opts ...grpc.CallOption) (*GetBinanceTimeSeriesResponse, error)
}

type binanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBinanceServiceClient(cc grpc.ClientConnInterface) BinanceServiceClient {
	return &binanceServiceClient{cc}
}

func (c *binanceServiceClient) GetTimeSeries(ctx context.Context, in *GetBinanceTimeSeriesRequest, opts ...grpc.CallOption) (*GetBinanceTimeSeriesResponse, error) {
	out := new(GetBinanceTimeSeriesResponse)
	err := c.cc.Invoke(ctx, BinanceService_GetTimeSeries_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BinanceServiceServer is the server API for BinanceService service.
// All implementations must embed UnimplementedBinanceServiceServer
// for forward compatibility
type BinanceServiceServer interface {
	// Get time series data without technical indicators
	GetTimeSeries(context.Context, *GetBinanceTimeSeriesRequest) (*GetBinanceTimeSeriesResponse, error)
	mustEmbedUnimplementedBinanceServiceServer()
}

// UnimplementedBinanceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBinanceServiceServer struct {
}

func (UnimplementedBinanceServiceServer) GetTimeSeries(context.Context, *GetBinanceTimeSeriesRequest) (*GetBinanceTimeSeriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeSeries not implemented")
}
func (UnimplementedBinanceServiceServer) mustEmbedUnimplementedBinanceServiceServer() {}

// UnsafeBinanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BinanceServiceServer will
// result in compilation errors.
type UnsafeBinanceServiceServer interface {
	mustEmbedUnimplementedBinanceServiceServer()
}

func RegisterBinanceServiceServer(s grpc.ServiceRegistrar, srv BinanceServiceServer) {
	s.RegisterService(&BinanceService_ServiceDesc, srv)
}

func _BinanceService_GetTimeSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBinanceTimeSeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinanceServiceServer).GetTimeSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinanceService_GetTimeSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinanceServiceServer).GetTimeSeries(ctx, req.(*GetBinanceTimeSeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BinanceService_ServiceDesc is the grpc.ServiceDesc for BinanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BinanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "finazon.BinanceService",
	HandlerType: (*BinanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTimeSeries",
			Handler:    _BinanceService_GetTimeSeries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "binance.proto",
}
