// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: sec.proto

package finazon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecFillingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cik           int64    `protobuf:"varint,1,opt,name=cik,proto3" json:"cik,omitempty"`
	Ticker        string   `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	FormType      []string `protobuf:"bytes,4,rep,name=form_type,json=formType,proto3" json:"form_type,omitempty"`
	FilledFromTs  int64    `protobuf:"varint,5,opt,name=filled_from_ts,json=filledFromTs,proto3" json:"filled_from_ts,omitempty"`
	FilledToTs    int64    `protobuf:"varint,6,opt,name=filled_to_ts,json=filledToTs,proto3" json:"filled_to_ts,omitempty"`
	Page          int32    `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32    `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cqs           string   `protobuf:"bytes,9,opt,name=cqs,proto3" json:"cqs,omitempty"`
	Cusip         string   `protobuf:"bytes,10,opt,name=cusip,proto3" json:"cusip,omitempty"`
	Isin          string   `protobuf:"bytes,11,opt,name=isin,proto3" json:"isin,omitempty"`
	CompositeFigi string   `protobuf:"bytes,12,opt,name=composite_figi,json=compositeFigi,proto3" json:"composite_figi,omitempty"`
	ShareFigi     string   `protobuf:"bytes,13,opt,name=share_figi,json=shareFigi,proto3" json:"share_figi,omitempty"`
	Lei           string   `protobuf:"bytes,14,opt,name=lei,proto3" json:"lei,omitempty"`
}

func (x *GetSecFillingsRequest) Reset() {
	*x = GetSecFillingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSecFillingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecFillingsRequest) ProtoMessage() {}

func (x *GetSecFillingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecFillingsRequest.ProtoReflect.Descriptor instead.
func (*GetSecFillingsRequest) Descriptor() ([]byte, []int) {
	return file_sec_proto_rawDescGZIP(), []int{0}
}

func (x *GetSecFillingsRequest) GetCik() int64 {
	if x != nil {
		return x.Cik
	}
	return 0
}

func (x *GetSecFillingsRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *GetSecFillingsRequest) GetFormType() []string {
	if x != nil {
		return x.FormType
	}
	return nil
}

func (x *GetSecFillingsRequest) GetFilledFromTs() int64 {
	if x != nil {
		return x.FilledFromTs
	}
	return 0
}

func (x *GetSecFillingsRequest) GetFilledToTs() int64 {
	if x != nil {
		return x.FilledToTs
	}
	return 0
}

func (x *GetSecFillingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSecFillingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetSecFillingsRequest) GetCqs() string {
	if x != nil {
		return x.Cqs
	}
	return ""
}

func (x *GetSecFillingsRequest) GetCusip() string {
	if x != nil {
		return x.Cusip
	}
	return ""
}

func (x *GetSecFillingsRequest) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

func (x *GetSecFillingsRequest) GetCompositeFigi() string {
	if x != nil {
		return x.CompositeFigi
	}
	return ""
}

func (x *GetSecFillingsRequest) GetShareFigi() string {
	if x != nil {
		return x.ShareFigi
	}
	return ""
}

func (x *GetSecFillingsRequest) GetLei() string {
	if x != nil {
		return x.Lei
	}
	return ""
}

type GetSecFillingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*SecFillingsItem `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *GetSecFillingsResponse) Reset() {
	*x = GetSecFillingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSecFillingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecFillingsResponse) ProtoMessage() {}

func (x *GetSecFillingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecFillingsResponse.ProtoReflect.Descriptor instead.
func (*GetSecFillingsResponse) Descriptor() ([]byte, []int) {
	return file_sec_proto_rawDescGZIP(), []int{1}
}

func (x *GetSecFillingsResponse) GetResult() []*SecFillingsItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type SecFillingsItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticker    []string         `protobuf:"bytes,1,rep,name=ticker,proto3" json:"ticker,omitempty"`
	Cik       int64            `protobuf:"varint,2,opt,name=cik,proto3" json:"cik,omitempty"`
	FormType  string           `protobuf:"bytes,3,opt,name=form_type,json=formType,proto3" json:"form_type,omitempty"`
	FiledAt   int64            `protobuf:"varint,4,opt,name=filed_at,json=filedAt,proto3" json:"filed_at,omitempty"`
	FilingUrl string           `protobuf:"bytes,5,opt,name=filing_url,json=filingUrl,proto3" json:"filing_url,omitempty"`
	Files     []*SecFilingFile `protobuf:"bytes,6,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *SecFillingsItem) Reset() {
	*x = SecFillingsItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sec_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecFillingsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecFillingsItem) ProtoMessage() {}

func (x *SecFillingsItem) ProtoReflect() protoreflect.Message {
	mi := &file_sec_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecFillingsItem.ProtoReflect.Descriptor instead.
func (*SecFillingsItem) Descriptor() ([]byte, []int) {
	return file_sec_proto_rawDescGZIP(), []int{2}
}

func (x *SecFillingsItem) GetTicker() []string {
	if x != nil {
		return x.Ticker
	}
	return nil
}

func (x *SecFillingsItem) GetCik() int64 {
	if x != nil {
		return x.Cik
	}
	return 0
}

func (x *SecFillingsItem) GetFormType() string {
	if x != nil {
		return x.FormType
	}
	return ""
}

func (x *SecFillingsItem) GetFiledAt() int64 {
	if x != nil {
		return x.FiledAt
	}
	return 0
}

func (x *SecFillingsItem) GetFilingUrl() string {
	if x != nil {
		return x.FilingUrl
	}
	return ""
}

func (x *SecFillingsItem) GetFiles() []*SecFilingFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type SecFilingFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size int32  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Url  string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SecFilingFile) Reset() {
	*x = SecFilingFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sec_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecFilingFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecFilingFile) ProtoMessage() {}

func (x *SecFilingFile) ProtoReflect() protoreflect.Message {
	mi := &file_sec_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecFilingFile.ProtoReflect.Descriptor instead.
func (*SecFilingFile) Descriptor() ([]byte, []int) {
	return file_sec_proto_rawDescGZIP(), []int{3}
}

func (x *SecFilingFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecFilingFile) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SecFilingFile) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SecFilingFile) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_sec_proto protoreflect.FileDescriptor

var file_sec_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x69, 0x6e,
	0x61, 0x7a, 0x6f, 0x6e, 0x22, 0xeb, 0x02, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x46,
	0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x69, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x69, 0x6b,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x6f, 0x72, 0x6d,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x66, 0x6f, 0x72,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x5f,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x66,
	0x69, 0x6c, 0x6c, 0x65, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x54, 0x73, 0x12, 0x20, 0x0a, 0x0c, 0x66,
	0x69, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x5f, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x54, 0x6f, 0x54, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x63, 0x71, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x71, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x75, 0x73, 0x69, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x75, 0x73, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x69, 0x6e, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x69, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x67, 0x69, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x65, 0x46, 0x69, 0x67,
	0x69, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x66, 0x69, 0x67, 0x69, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x61, 0x72, 0x65, 0x46, 0x69, 0x67, 0x69,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x69, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c,
	0x65, 0x69, 0x22, 0x4a, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x46, 0x69, 0x6c, 0x6c,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66,
	0x69, 0x6e, 0x61, 0x7a, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x63, 0x46, 0x69, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xc0,
	0x01, 0x0a, 0x0f, 0x53, 0x65, 0x63, 0x46, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x69, 0x6b, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x6f, 0x72, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x69, 0x6c,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x69, 0x6c,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x69, 0x6e, 0x67,
	0x55, 0x72, 0x6c, 0x12, 0x2c, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x7a, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x63,
	0x46, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x22, 0x5d, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x46, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c,
	0x32, 0x5d, 0x0a, 0x0a, 0x53, 0x65, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1e, 0x2e, 0x66,
	0x69, 0x6e, 0x61, 0x7a, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x46, 0x69, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x66,
	0x69, 0x6e, 0x61, 0x7a, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x63, 0x46, 0x69, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sec_proto_rawDescOnce sync.Once
	file_sec_proto_rawDescData = file_sec_proto_rawDesc
)

func file_sec_proto_rawDescGZIP() []byte {
	file_sec_proto_rawDescOnce.Do(func() {
		file_sec_proto_rawDescData = protoimpl.X.CompressGZIP(file_sec_proto_rawDescData)
	})
	return file_sec_proto_rawDescData
}

var file_sec_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sec_proto_goTypes = []interface{}{
	(*GetSecFillingsRequest)(nil),  // 0: finazon.GetSecFillingsRequest
	(*GetSecFillingsResponse)(nil), // 1: finazon.GetSecFillingsResponse
	(*SecFillingsItem)(nil),        // 2: finazon.SecFillingsItem
	(*SecFilingFile)(nil),          // 3: finazon.SecFilingFile
}
var file_sec_proto_depIdxs = []int32{
	2, // 0: finazon.GetSecFillingsResponse.result:type_name -> finazon.SecFillingsItem
	3, // 1: finazon.SecFillingsItem.files:type_name -> finazon.SecFilingFile
	0, // 2: finazon.SecService.GetFilings:input_type -> finazon.GetSecFillingsRequest
	1, // 3: finazon.SecService.GetFilings:output_type -> finazon.GetSecFillingsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sec_proto_init() }
func file_sec_proto_init() {
	if File_sec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSecFillingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSecFillingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sec_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecFillingsItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sec_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecFilingFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sec_proto_goTypes,
		DependencyIndexes: file_sec_proto_depIdxs,
		MessageInfos:      file_sec_proto_msgTypes,
	}.Build()
	File_sec_proto = out.File
	file_sec_proto_rawDesc = nil
	file_sec_proto_goTypes = nil
	file_sec_proto_depIdxs = nil
}
